# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCDxiyxCLQVfiVsRT2oE2Ymu7zCWyiG0
"""

import sqlite3
import pandas as pd

# 1. Create (or connect to) a database file
# This creates a file named 'my_portfolio.db' automatically!
conn = sqlite3.connect('my_portfolio.db')

# 2. Create a table
query = """
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY,
    project_name TEXT,
    technology TEXT
)
"""
conn.execute(query)

# 3. Insert your first project record
conn.execute("INSERT INTO projects (project_name, technology) VALUES ('Data Pipeline', 'Python')")
conn.commit()

# 4. Prove it worked by reading it into a Pandas Dataframe
df = pd.read_sql_query("SELECT * FROM projects", conn)
print(df)

import requests
import pandas as pd

# Fetch live Bitcoin price data
url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1"
response = requests.get(url)
data = response.json()

# Convert to a DataFrame (Transformation)
df = pd.DataFrame(data)[['name', 'symbol', 'current_price', 'market_cap']]
print(df.head())

import sqlite3

# Connect to a database file (it creates it if it doesn't exist)
conn = sqlite3.connect('crypto_warehouse.db')

# Load the data into a SQL table
df.to_sql('top_cryptos', conn, if_exists='replace', index=False)

print("Data successfully loaded into SQLite Warehouse!")